version: '3.9'

services:
  api:
    build: .
    container_name: api_project
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - ./app:/app/app
      - ./app.db:/app/app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
